// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package streaming_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// StreamingClient is the client API for Streaming service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamingClient interface {
	ConsumeStream(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (Streaming_ConsumeStreamClient, error)
	ProduceStream(ctx context.Context, opts ...grpc.CallOption) (Streaming_ProduceStreamClient, error)
	GetMetadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error)
}

type streamingClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamingClient(cc grpc.ClientConnInterface) StreamingClient {
	return &streamingClient{cc}
}

func (c *streamingClient) ConsumeStream(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (Streaming_ConsumeStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Streaming_serviceDesc.Streams[0], "/streaming.v1.Streaming/ConsumeStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamingConsumeStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Streaming_ConsumeStreamClient interface {
	Recv() (*ConsumeResponse, error)
	grpc.ClientStream
}

type streamingConsumeStreamClient struct {
	grpc.ClientStream
}

func (x *streamingConsumeStreamClient) Recv() (*ConsumeResponse, error) {
	m := new(ConsumeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamingClient) ProduceStream(ctx context.Context, opts ...grpc.CallOption) (Streaming_ProduceStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Streaming_serviceDesc.Streams[1], "/streaming.v1.Streaming/ProduceStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamingProduceStreamClient{stream}
	return x, nil
}

type Streaming_ProduceStreamClient interface {
	Send(*ProduceRequest) error
	CloseAndRecv() (*ProduceResponse, error)
	grpc.ClientStream
}

type streamingProduceStreamClient struct {
	grpc.ClientStream
}

func (x *streamingProduceStreamClient) Send(m *ProduceRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamingProduceStreamClient) CloseAndRecv() (*ProduceResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ProduceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamingClient) GetMetadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error) {
	out := new(MetadataResponse)
	err := c.cc.Invoke(ctx, "/streaming.v1.Streaming/GetMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamingServer is the server API for Streaming service.
// All implementations must embed UnimplementedStreamingServer
// for forward compatibility
type StreamingServer interface {
	ConsumeStream(*ConsumeRequest, Streaming_ConsumeStreamServer) error
	ProduceStream(Streaming_ProduceStreamServer) error
	GetMetadata(context.Context, *MetadataRequest) (*MetadataResponse, error)
	mustEmbedUnimplementedStreamingServer()
}

// UnimplementedStreamingServer must be embedded to have forward compatible implementations.
type UnimplementedStreamingServer struct {
}

func (UnimplementedStreamingServer) ConsumeStream(*ConsumeRequest, Streaming_ConsumeStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ConsumeStream not implemented")
}
func (UnimplementedStreamingServer) ProduceStream(Streaming_ProduceStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ProduceStream not implemented")
}
func (UnimplementedStreamingServer) GetMetadata(context.Context, *MetadataRequest) (*MetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedStreamingServer) mustEmbedUnimplementedStreamingServer() {}

// UnsafeStreamingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamingServer will
// result in compilation errors.
type UnsafeStreamingServer interface {
	mustEmbedUnimplementedStreamingServer()
}

func RegisterStreamingServer(s *grpc.Server, srv StreamingServer) {
	s.RegisterService(&_Streaming_serviceDesc, srv)
}

func _Streaming_ConsumeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConsumeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamingServer).ConsumeStream(m, &streamingConsumeStreamServer{stream})
}

type Streaming_ConsumeStreamServer interface {
	Send(*ConsumeResponse) error
	grpc.ServerStream
}

type streamingConsumeStreamServer struct {
	grpc.ServerStream
}

func (x *streamingConsumeStreamServer) Send(m *ConsumeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Streaming_ProduceStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamingServer).ProduceStream(&streamingProduceStreamServer{stream})
}

type Streaming_ProduceStreamServer interface {
	SendAndClose(*ProduceResponse) error
	Recv() (*ProduceRequest, error)
	grpc.ServerStream
}

type streamingProduceStreamServer struct {
	grpc.ServerStream
}

func (x *streamingProduceStreamServer) SendAndClose(m *ProduceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamingProduceStreamServer) Recv() (*ProduceRequest, error) {
	m := new(ProduceRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Streaming_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamingServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streaming.v1.Streaming/GetMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamingServer).GetMetadata(ctx, req.(*MetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Streaming_serviceDesc = grpc.ServiceDesc{
	ServiceName: "streaming.v1.Streaming",
	HandlerType: (*StreamingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetadata",
			Handler:    _Streaming_GetMetadata_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConsumeStream",
			Handler:       _Streaming_ConsumeStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ProduceStream",
			Handler:       _Streaming_ProduceStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/streaming/v1/streaming.proto",
}

// LBResolverHelperClient is the client API for LBResolverHelper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LBResolverHelperClient interface {
	GetServers(ctx context.Context, in *GetServersRequest, opts ...grpc.CallOption) (*GetServersResponse, error)
}

type lBResolverHelperClient struct {
	cc grpc.ClientConnInterface
}

func NewLBResolverHelperClient(cc grpc.ClientConnInterface) LBResolverHelperClient {
	return &lBResolverHelperClient{cc}
}

func (c *lBResolverHelperClient) GetServers(ctx context.Context, in *GetServersRequest, opts ...grpc.CallOption) (*GetServersResponse, error) {
	out := new(GetServersResponse)
	err := c.cc.Invoke(ctx, "/streaming.v1.LBResolverHelper/GetServers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LBResolverHelperServer is the server API for LBResolverHelper service.
// All implementations must embed UnimplementedLBResolverHelperServer
// for forward compatibility
type LBResolverHelperServer interface {
	GetServers(context.Context, *GetServersRequest) (*GetServersResponse, error)
	mustEmbedUnimplementedLBResolverHelperServer()
}

// UnimplementedLBResolverHelperServer must be embedded to have forward compatible implementations.
type UnimplementedLBResolverHelperServer struct {
}

func (UnimplementedLBResolverHelperServer) GetServers(context.Context, *GetServersRequest) (*GetServersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServers not implemented")
}
func (UnimplementedLBResolverHelperServer) mustEmbedUnimplementedLBResolverHelperServer() {}

// UnsafeLBResolverHelperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LBResolverHelperServer will
// result in compilation errors.
type UnsafeLBResolverHelperServer interface {
	mustEmbedUnimplementedLBResolverHelperServer()
}

func RegisterLBResolverHelperServer(s *grpc.Server, srv LBResolverHelperServer) {
	s.RegisterService(&_LBResolverHelper_serviceDesc, srv)
}

func _LBResolverHelper_GetServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LBResolverHelperServer).GetServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streaming.v1.LBResolverHelper/GetServers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LBResolverHelperServer).GetServers(ctx, req.(*GetServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LBResolverHelper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "streaming.v1.LBResolverHelper",
	HandlerType: (*LBResolverHelperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServers",
			Handler:    _LBResolverHelper_GetServers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/streaming/v1/streaming.proto",
}

// FollowerResolverHelperClient is the client API for FollowerResolverHelper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FollowerResolverHelperClient interface {
	GetFollowers(ctx context.Context, in *GetFollowersRequest, opts ...grpc.CallOption) (*GetFollowersResponse, error)
}

type followerResolverHelperClient struct {
	cc grpc.ClientConnInterface
}

func NewFollowerResolverHelperClient(cc grpc.ClientConnInterface) FollowerResolverHelperClient {
	return &followerResolverHelperClient{cc}
}

func (c *followerResolverHelperClient) GetFollowers(ctx context.Context, in *GetFollowersRequest, opts ...grpc.CallOption) (*GetFollowersResponse, error) {
	out := new(GetFollowersResponse)
	err := c.cc.Invoke(ctx, "/streaming.v1.FollowerResolverHelper/GetFollowers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FollowerResolverHelperServer is the server API for FollowerResolverHelper service.
// All implementations must embed UnimplementedFollowerResolverHelperServer
// for forward compatibility
type FollowerResolverHelperServer interface {
	GetFollowers(context.Context, *GetFollowersRequest) (*GetFollowersResponse, error)
	mustEmbedUnimplementedFollowerResolverHelperServer()
}

// UnimplementedFollowerResolverHelperServer must be embedded to have forward compatible implementations.
type UnimplementedFollowerResolverHelperServer struct {
}

func (UnimplementedFollowerResolverHelperServer) GetFollowers(context.Context, *GetFollowersRequest) (*GetFollowersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowers not implemented")
}
func (UnimplementedFollowerResolverHelperServer) mustEmbedUnimplementedFollowerResolverHelperServer() {
}

// UnsafeFollowerResolverHelperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FollowerResolverHelperServer will
// result in compilation errors.
type UnsafeFollowerResolverHelperServer interface {
	mustEmbedUnimplementedFollowerResolverHelperServer()
}

func RegisterFollowerResolverHelperServer(s *grpc.Server, srv FollowerResolverHelperServer) {
	s.RegisterService(&_FollowerResolverHelper_serviceDesc, srv)
}

func _FollowerResolverHelper_GetFollowers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowerResolverHelperServer).GetFollowers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streaming.v1.FollowerResolverHelper/GetFollowers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowerResolverHelperServer).GetFollowers(ctx, req.(*GetFollowersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FollowerResolverHelper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "streaming.v1.FollowerResolverHelper",
	HandlerType: (*FollowerResolverHelperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFollowers",
			Handler:    _FollowerResolverHelper_GetFollowers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/streaming/v1/streaming.proto",
}
